version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.2.0
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  test:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - aws-cli/setup:
          role-arn: "${AWS_CIRCLECI_ROLE_ARN}"
          aws-region: AWS_REGION
          profile-name: "playground"
          role-session-name: CircleSession
          session-duration: '1800'
      - helm/install-helm-client:
          version: v3.2.0
      - run:
          name: Update kubeconfig
          command: |
            aws eks update-kubeconfig --name ${EKS_CLUSTER}
      - run:
          name: Install test chart
          command: |
            helm install --debug --atomic --wait --create-namespace -n deploy-test deploy-test test
            helm uninstall -n deploy-test deploy-test

workflows:
  test:
    jobs:
      - test:
          context: playground
